#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l vmem=16gb
#PBS -M siwxu@iu.edu
#PBS -m abe
#PBS -l walltime=48:00:00

module load freebayes/1.2.0
freebayes -f /N/dc2/projects/ngs/users/siwxu/database/10X/genome.fa -C 200 -q 20 -iXu -m 30 \
--pooled-continuous --min-alternate-fraction 0.01 -r 1 \
/N/dc2/projects/ngs/projects/iucmg/10X_singleCell/Nova_S2_008/Analysis/0661-5_CD138Plus/outs/possorted_genome_bam.bam \
> /N/dc2/projects/ngs/users/siwxu/projects/scRNA/data/5/CD138plus/SNP_MAF001_chr1.vcf
