#!/bin/bash
#PBS -l nodes=1:ppn=8
#PBS -l walltime=48:00:00
#PBS -l vmem=32gb
#PBS -M siwxu@iu.edu
#PBS -m abe

module load samtools/1.9

n=0
cat /N/dc2/projects/ngs/users/siwxu/projects/scRNA/data/SNP.bed | while read line
do
line_arr=( $line )
pod=${line_arr[1]}
sta=${line_arr[0]}
grep "$bc" /N/dc2/projects/ngs/users/siwxu/projects/scRNA/data/$gene > /N/dc2/projects/ngs/users/siwxu/projects/scRNA/data/temp/$gene
((n=n+1))
echo $n
done

